
// This file has been generated by the GUI designer. Do not modify.
namespace AccountingODS
{
	public partial class InvoiceDetailDialog
	{
		private global::Gtk.Table table5;

		private global::Gtk.Table table6;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview;

		private global::Gtk.Label label2;

		private global::Gtk.Table table7;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Table table10;

		private global::Gtk.Label label21;

		private global::Gtk.Label labelInvoiceDate;

		private global::Gtk.Table table11;

		private global::Gtk.Label label24;

		private global::Gtk.Label labelMaturityDate;

		private global::Gtk.Table table12;

		private global::Gtk.Label label5;

		private global::Gtk.Label label8;

		private global::Gtk.Label labelNumber;

		private global::Gtk.Label labelType;

		private global::Gtk.Table table8;

		private global::Gtk.Label label10;

		private global::Gtk.Label label11;

		private global::Gtk.Label label9;

		private global::Gtk.Label labelDebtorAdress;

		private global::Gtk.Label labelDebtorName;

		private global::Gtk.Label labelDebtorZIP;

		private global::Gtk.Table table9;

		private global::Gtk.Label label15;

		private global::Gtk.Label label16;

		private global::Gtk.Label label17;

		private global::Gtk.Label labelCreditorAdress;

		private global::Gtk.Label labelCreditorName;

		private global::Gtk.Label labelCreditorZIP;

		private global::Gtk.Button buttonCancel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget AccountingODS.InvoiceDetailDialog
			this.Name = "AccountingODS.InvoiceDetailDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child AccountingODS.InvoiceDetailDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table5 = new global::Gtk.Table(((uint)(1)), ((uint)(2)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.table6 = new global::Gtk.Table(((uint)(2)), ((uint)(1)), false);
			this.table6.Name = "table6";
			this.table6.RowSpacing = ((uint)(6));
			this.table6.ColumnSpacing = ((uint)(6));
			// Container child table6.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview = new global::Gtk.NodeView();
			this.nodeview.CanFocus = true;
			this.nodeview.Name = "nodeview";
			this.GtkScrolledWindow.Add(this.nodeview);
			this.table6.Add(this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table6[this.GtkScrolledWindow]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Invoice items");
			this.table6.Add(this.label2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table6[this.label2]));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table5.Add(this.table6);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table5[this.table6]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			// Container child table5.Gtk.Table+TableChild
			this.table7 = new global::Gtk.Table(((uint)(10)), ((uint)(1)), false);
			this.table7.Name = "table7";
			this.table7.RowSpacing = ((uint)(6));
			this.table7.ColumnSpacing = ((uint)(6));
			// Container child table7.Gtk.Table+TableChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.table7.Add(this.hseparator1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table7[this.hseparator1]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.table7.Add(this.hseparator2);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table7[this.hseparator2]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.table7.Add(this.hseparator3);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table7[this.hseparator3]));
			w8.TopAttach = ((uint)(7));
			w8.BottomAttach = ((uint)(8));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Debtor");
			this.table7.Add(this.label3);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table7[this.label3]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Creditor");
			this.table7.Add(this.label4);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table7[this.label4]));
			w10.TopAttach = ((uint)(5));
			w10.BottomAttach = ((uint)(6));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.table10 = new global::Gtk.Table(((uint)(1)), ((uint)(2)), false);
			this.table10.Name = "table10";
			this.table10.RowSpacing = ((uint)(6));
			this.table10.ColumnSpacing = ((uint)(6));
			// Container child table10.Gtk.Table+TableChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Invoice date:");
			this.table10.Add(this.label21);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table10[this.label21]));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table10.Gtk.Table+TableChild
			this.labelInvoiceDate = new global::Gtk.Label();
			this.labelInvoiceDate.Name = "labelInvoiceDate";
			this.labelInvoiceDate.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.table10.Add(this.labelInvoiceDate);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table10[this.labelInvoiceDate]));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table7.Add(this.table10);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table7[this.table10]));
			w13.TopAttach = ((uint)(8));
			w13.BottomAttach = ((uint)(9));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.table11 = new global::Gtk.Table(((uint)(1)), ((uint)(2)), false);
			this.table11.Name = "table11";
			this.table11.RowSpacing = ((uint)(6));
			this.table11.ColumnSpacing = ((uint)(6));
			// Container child table11.Gtk.Table+TableChild
			this.label24 = new global::Gtk.Label();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("Maturity date:");
			this.table11.Add(this.label24);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table11[this.label24]));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table11.Gtk.Table+TableChild
			this.labelMaturityDate = new global::Gtk.Label();
			this.labelMaturityDate.Name = "labelMaturityDate";
			this.labelMaturityDate.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.table11.Add(this.labelMaturityDate);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table11[this.labelMaturityDate]));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table7.Add(this.table11);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table7[this.table11]));
			w16.TopAttach = ((uint)(9));
			w16.BottomAttach = ((uint)(10));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.table12 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table12.Name = "table12";
			this.table12.RowSpacing = ((uint)(6));
			this.table12.ColumnSpacing = ((uint)(6));
			// Container child table12.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Invoice type:");
			this.table12.Add(this.label5);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table12[this.label5]));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Invoice number:");
			this.table12.Add(this.label8);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table12[this.label8]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.labelNumber = new global::Gtk.Label();
			this.labelNumber.Name = "labelNumber";
			this.labelNumber.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.table12.Add(this.labelNumber);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table12[this.labelNumber]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table12.Gtk.Table+TableChild
			this.labelType = new global::Gtk.Label();
			this.labelType.Name = "labelType";
			this.labelType.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.table12.Add(this.labelType);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table12[this.labelType]));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table7.Add(this.table12);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table7[this.table12]));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.table8 = new global::Gtk.Table(((uint)(2)), ((uint)(3)), false);
			this.table8.Name = "table8";
			this.table8.RowSpacing = ((uint)(6));
			this.table8.ColumnSpacing = ((uint)(6));
			// Container child table8.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Adress");
			this.table8.Add(this.label10);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table8[this.label10]));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("ZIP code");
			this.table8.Add(this.label11);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table8[this.label11]));
			w23.LeftAttach = ((uint)(2));
			w23.RightAttach = ((uint)(3));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Name");
			this.table8.Add(this.label9);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table8[this.label9]));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.labelDebtorAdress = new global::Gtk.Label();
			this.labelDebtorAdress.Name = "labelDebtorAdress";
			this.labelDebtorAdress.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.table8.Add(this.labelDebtorAdress);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table8[this.labelDebtorAdress]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.labelDebtorName = new global::Gtk.Label();
			this.labelDebtorName.Name = "labelDebtorName";
			this.labelDebtorName.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.table8.Add(this.labelDebtorName);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table8[this.labelDebtorName]));
			w26.TopAttach = ((uint)(1));
			w26.BottomAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.labelDebtorZIP = new global::Gtk.Label();
			this.labelDebtorZIP.Name = "labelDebtorZIP";
			this.labelDebtorZIP.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.table8.Add(this.labelDebtorZIP);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table8[this.labelDebtorZIP]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.LeftAttach = ((uint)(2));
			w27.RightAttach = ((uint)(3));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table7.Add(this.table8);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table7[this.table8]));
			w28.TopAttach = ((uint)(3));
			w28.BottomAttach = ((uint)(4));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.table9 = new global::Gtk.Table(((uint)(2)), ((uint)(3)), false);
			this.table9.Name = "table9";
			this.table9.RowSpacing = ((uint)(6));
			this.table9.ColumnSpacing = ((uint)(6));
			// Container child table9.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Name");
			this.table9.Add(this.label15);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table9[this.label15]));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Adress");
			this.table9.Add(this.label16);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table9[this.label16]));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("ZIP code");
			this.table9.Add(this.label17);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table9[this.label17]));
			w31.LeftAttach = ((uint)(2));
			w31.RightAttach = ((uint)(3));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.labelCreditorAdress = new global::Gtk.Label();
			this.labelCreditorAdress.Name = "labelCreditorAdress";
			this.labelCreditorAdress.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.table9.Add(this.labelCreditorAdress);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table9[this.labelCreditorAdress]));
			w32.TopAttach = ((uint)(1));
			w32.BottomAttach = ((uint)(2));
			w32.LeftAttach = ((uint)(1));
			w32.RightAttach = ((uint)(2));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.labelCreditorName = new global::Gtk.Label();
			this.labelCreditorName.Name = "labelCreditorName";
			this.labelCreditorName.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.table9.Add(this.labelCreditorName);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table9[this.labelCreditorName]));
			w33.TopAttach = ((uint)(1));
			w33.BottomAttach = ((uint)(2));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table9.Gtk.Table+TableChild
			this.labelCreditorZIP = new global::Gtk.Label();
			this.labelCreditorZIP.Name = "labelCreditorZIP";
			this.labelCreditorZIP.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.table9.Add(this.labelCreditorZIP);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table9[this.labelCreditorZIP]));
			w34.TopAttach = ((uint)(1));
			w34.BottomAttach = ((uint)(2));
			w34.LeftAttach = ((uint)(2));
			w34.RightAttach = ((uint)(3));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table7.Add(this.table9);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table7[this.table9]));
			w35.TopAttach = ((uint)(6));
			w35.BottomAttach = ((uint)(7));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table5.Add(this.table7);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table5[this.table7]));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add(this.table5);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(w1[this.table5]));
			w37.Position = 0;
			// Internal child AccountingODS.InvoiceDetailDialog.ActionArea
			global::Gtk.HButtonBox w38 = this.ActionArea;
			w38.Name = "dialog1_ActionArea";
			w38.Spacing = 10;
			w38.BorderWidth = ((uint)(5));
			w38.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Close");
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w39 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w38[this.buttonCancel]));
			w39.Expand = false;
			w39.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 819;
			this.DefaultHeight = 435;
			this.Show();
			this.buttonCancel.Clicked += new global::System.EventHandler(this.OnButtonCancelClicked);
		}
	}
}
