
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table8;

	private global::Gtk.Table table12;

	private global::Gtk.Label labelCreditTitle;

	private global::Gtk.ScrolledWindow scrolledwindow2;

	private global::Gtk.NodeView nodeviewCredit;

	private global::Gtk.Table table6;

	private global::Gtk.Button buttonShowInvoiceDetail;

	private global::Gtk.Table table11;

	private global::Gtk.Entry entryInvoiceItemName;

	private global::Gtk.Label label11;

	private global::Gtk.Table table3;

	private global::Gtk.Button buttonAddInvoice;

	private global::Gtk.Calendar calendarInvoiceDate;

	private global::Gtk.Calendar calendarMaturityDate;

	private global::Gtk.ComboBox comboboxType;

	private global::Gtk.Label label10;

	private global::Gtk.Label label8;

	private global::Gtk.Label label9;

	private global::Gtk.Table table2;

	private global::Gtk.Entry entryCreditorAdress;

	private global::Gtk.Entry entryCreditorName;

	private global::Gtk.Entry entryCreditorZip;

	private global::Gtk.Entry entryDebtorAdress;

	private global::Gtk.Entry entryDebtorName;

	private global::Gtk.Entry entryDebtorZip;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	private global::Gtk.Label label6;

	private global::Gtk.Label label7;

	private global::Gtk.Table table4;

	private global::Gtk.Entry entryInvoiceNumber;

	private global::Gtk.Label label1;

	private global::Gtk.Table table9;

	private global::Gtk.Label labelDebtTitle;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.NodeView nodeviewDebt;

	private global::Gtk.Table table5;

	private global::Gtk.Table table10;

	private global::Gtk.Entry entryInvoiceItemCost;

	private global::Gtk.Label label12;

	private global::Gtk.Table table7;

	private global::Gtk.Button buttonAddInvoiceItem;

	private global::Gtk.Button buttonDeleteInvoice;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(6));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table8 = new global::Gtk.Table(((uint)(1)), ((uint)(3)), false);
		this.table8.Name = "table8";
		this.table8.RowSpacing = ((uint)(6));
		this.table8.ColumnSpacing = ((uint)(6));
		// Container child table8.Gtk.Table+TableChild
		this.table12 = new global::Gtk.Table(((uint)(3)), ((uint)(1)), false);
		this.table12.Name = "table12";
		this.table12.RowSpacing = ((uint)(6));
		this.table12.ColumnSpacing = ((uint)(6));
		// Container child table12.Gtk.Table+TableChild
		this.labelCreditTitle = new global::Gtk.Label();
		this.labelCreditTitle.Name = "labelCreditTitle";
		this.labelCreditTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Credit");
		this.table12.Add(this.labelCreditTitle);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table12[this.labelCreditTitle]));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table12.Gtk.Table+TableChild
		this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow2.CanFocus = true;
		this.scrolledwindow2.Name = "scrolledwindow2";
		this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow2.Gtk.Container+ContainerChild
		this.nodeviewCredit = new global::Gtk.NodeView();
		this.nodeviewCredit.CanFocus = true;
		this.nodeviewCredit.Name = "nodeviewCredit";
		this.scrolledwindow2.Add(this.nodeviewCredit);
		this.table12.Add(this.scrolledwindow2);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table12[this.scrolledwindow2]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table12.Gtk.Table+TableChild
		this.table6 = new global::Gtk.Table(((uint)(2)), ((uint)(1)), false);
		this.table6.Name = "table6";
		this.table6.RowSpacing = ((uint)(6));
		this.table6.ColumnSpacing = ((uint)(6));
		// Container child table6.Gtk.Table+TableChild
		this.buttonShowInvoiceDetail = new global::Gtk.Button();
		this.buttonShowInvoiceDetail.CanFocus = true;
		this.buttonShowInvoiceDetail.Name = "buttonShowInvoiceDetail";
		this.buttonShowInvoiceDetail.UseUnderline = true;
		this.buttonShowInvoiceDetail.Label = global::Mono.Unix.Catalog.GetString("Show invoice detail");
		this.table6.Add(this.buttonShowInvoiceDetail);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table6[this.buttonShowInvoiceDetail]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.table11 = new global::Gtk.Table(((uint)(1)), ((uint)(2)), false);
		this.table11.Name = "table11";
		this.table11.RowSpacing = ((uint)(6));
		this.table11.ColumnSpacing = ((uint)(6));
		// Container child table11.Gtk.Table+TableChild
		this.entryInvoiceItemName = new global::Gtk.Entry();
		this.entryInvoiceItemName.CanFocus = true;
		this.entryInvoiceItemName.Name = "entryInvoiceItemName";
		this.entryInvoiceItemName.IsEditable = true;
		this.entryInvoiceItemName.InvisibleChar = '•';
		this.table11.Add(this.entryInvoiceItemName);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table11[this.entryInvoiceItemName]));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table11.Gtk.Table+TableChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Item text");
		this.table11.Add(this.label11);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table11[this.label11]));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table6.Add(this.table11);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table6[this.table11]));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table12.Add(this.table6);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table12[this.table6]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table8.Add(this.table12);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table8[this.table12]));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table8.Gtk.Table+TableChild
		this.table3 = new global::Gtk.Table(((uint)(9)), ((uint)(1)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.buttonAddInvoice = new global::Gtk.Button();
		this.buttonAddInvoice.CanFocus = true;
		this.buttonAddInvoice.Name = "buttonAddInvoice";
		this.buttonAddInvoice.UseUnderline = true;
		this.buttonAddInvoice.Label = global::Mono.Unix.Catalog.GetString("Add invoice");
		this.table3.Add(this.buttonAddInvoice);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3[this.buttonAddInvoice]));
		w10.TopAttach = ((uint)(8));
		w10.BottomAttach = ((uint)(9));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.calendarInvoiceDate = new global::Gtk.Calendar();
		this.calendarInvoiceDate.CanFocus = true;
		this.calendarInvoiceDate.Name = "calendarInvoiceDate";
		this.calendarInvoiceDate.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.table3.Add(this.calendarInvoiceDate);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3[this.calendarInvoiceDate]));
		w11.TopAttach = ((uint)(5));
		w11.BottomAttach = ((uint)(6));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.calendarMaturityDate = new global::Gtk.Calendar();
		this.calendarMaturityDate.CanFocus = true;
		this.calendarMaturityDate.Name = "calendarMaturityDate";
		this.calendarMaturityDate.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.table3.Add(this.calendarMaturityDate);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3[this.calendarMaturityDate]));
		w12.TopAttach = ((uint)(7));
		w12.BottomAttach = ((uint)(8));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.comboboxType = global::Gtk.ComboBox.NewText();
		this.comboboxType.Name = "comboboxType";
		this.table3.Add(this.comboboxType);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3[this.comboboxType]));
		w13.TopAttach = ((uint)(1));
		w13.BottomAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Invoice type");
		this.table3.Add(this.label10);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3[this.label10]));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Invoice date");
		this.table3.Add(this.label8);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3[this.label8]));
		w15.TopAttach = ((uint)(4));
		w15.BottomAttach = ((uint)(5));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Maturity date");
		this.table3.Add(this.label9);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3[this.label9]));
		w16.TopAttach = ((uint)(6));
		w16.BottomAttach = ((uint)(7));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.table2 = new global::Gtk.Table(((uint)(4)), ((uint)(3)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.entryCreditorAdress = new global::Gtk.Entry();
		this.entryCreditorAdress.CanFocus = true;
		this.entryCreditorAdress.Name = "entryCreditorAdress";
		this.entryCreditorAdress.IsEditable = true;
		this.entryCreditorAdress.InvisibleChar = '•';
		this.table2.Add(this.entryCreditorAdress);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2[this.entryCreditorAdress]));
		w17.TopAttach = ((uint)(3));
		w17.BottomAttach = ((uint)(4));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entryCreditorName = new global::Gtk.Entry();
		this.entryCreditorName.CanFocus = true;
		this.entryCreditorName.Name = "entryCreditorName";
		this.entryCreditorName.IsEditable = true;
		this.entryCreditorName.InvisibleChar = '•';
		this.table2.Add(this.entryCreditorName);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2[this.entryCreditorName]));
		w18.TopAttach = ((uint)(3));
		w18.BottomAttach = ((uint)(4));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entryCreditorZip = new global::Gtk.Entry();
		this.entryCreditorZip.CanFocus = true;
		this.entryCreditorZip.Name = "entryCreditorZip";
		this.entryCreditorZip.IsEditable = true;
		this.entryCreditorZip.InvisibleChar = '•';
		this.table2.Add(this.entryCreditorZip);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2[this.entryCreditorZip]));
		w19.TopAttach = ((uint)(3));
		w19.BottomAttach = ((uint)(4));
		w19.LeftAttach = ((uint)(2));
		w19.RightAttach = ((uint)(3));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entryDebtorAdress = new global::Gtk.Entry();
		this.entryDebtorAdress.CanFocus = true;
		this.entryDebtorAdress.Name = "entryDebtorAdress";
		this.entryDebtorAdress.IsEditable = true;
		this.entryDebtorAdress.InvisibleChar = '•';
		this.table2.Add(this.entryDebtorAdress);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2[this.entryDebtorAdress]));
		w20.TopAttach = ((uint)(1));
		w20.BottomAttach = ((uint)(2));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entryDebtorName = new global::Gtk.Entry();
		this.entryDebtorName.CanFocus = true;
		this.entryDebtorName.Name = "entryDebtorName";
		this.entryDebtorName.IsEditable = true;
		this.entryDebtorName.InvisibleChar = '•';
		this.table2.Add(this.entryDebtorName);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2[this.entryDebtorName]));
		w21.TopAttach = ((uint)(1));
		w21.BottomAttach = ((uint)(2));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.entryDebtorZip = new global::Gtk.Entry();
		this.entryDebtorZip.CanFocus = true;
		this.entryDebtorZip.Name = "entryDebtorZip";
		this.entryDebtorZip.IsEditable = true;
		this.entryDebtorZip.InvisibleChar = '•';
		this.table2.Add(this.entryDebtorZip);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2[this.entryDebtorZip]));
		w22.TopAttach = ((uint)(1));
		w22.BottomAttach = ((uint)(2));
		w22.LeftAttach = ((uint)(2));
		w22.RightAttach = ((uint)(3));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Debtor name");
		this.table2.Add(this.label2);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2[this.label2]));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Debtor adress");
		this.table2.Add(this.label3);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2[this.label3]));
		w24.LeftAttach = ((uint)(1));
		w24.RightAttach = ((uint)(2));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Debtor ZIP code");
		this.table2.Add(this.label4);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2[this.label4]));
		w25.LeftAttach = ((uint)(2));
		w25.RightAttach = ((uint)(3));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Creditor ZIP code");
		this.table2.Add(this.label5);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2[this.label5]));
		w26.TopAttach = ((uint)(2));
		w26.BottomAttach = ((uint)(3));
		w26.LeftAttach = ((uint)(2));
		w26.RightAttach = ((uint)(3));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Creditor name");
		this.table2.Add(this.label6);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table2[this.label6]));
		w27.TopAttach = ((uint)(2));
		w27.BottomAttach = ((uint)(3));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Creditor adress");
		this.table2.Add(this.label7);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table2[this.label7]));
		w28.TopAttach = ((uint)(2));
		w28.BottomAttach = ((uint)(3));
		w28.LeftAttach = ((uint)(1));
		w28.RightAttach = ((uint)(2));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table3.Add(this.table2);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table3[this.table2]));
		w29.TopAttach = ((uint)(3));
		w29.BottomAttach = ((uint)(4));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.table4 = new global::Gtk.Table(((uint)(2)), ((uint)(1)), true);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.entryInvoiceNumber = new global::Gtk.Entry();
		this.entryInvoiceNumber.CanFocus = true;
		this.entryInvoiceNumber.Name = "entryInvoiceNumber";
		this.entryInvoiceNumber.IsEditable = true;
		this.entryInvoiceNumber.InvisibleChar = '•';
		this.table4.Add(this.entryInvoiceNumber);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table4[this.entryInvoiceNumber]));
		w30.TopAttach = ((uint)(1));
		w30.BottomAttach = ((uint)(2));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Invoice number");
		this.table4.Add(this.label1);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table4[this.label1]));
		w31.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table3.Add(this.table4);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table3[this.table4]));
		w32.TopAttach = ((uint)(2));
		w32.BottomAttach = ((uint)(3));
		w32.XOptions = ((global::Gtk.AttachOptions)(4));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table8.Add(this.table3);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table8[this.table3]));
		w33.XOptions = ((global::Gtk.AttachOptions)(4));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table8.Gtk.Table+TableChild
		this.table9 = new global::Gtk.Table(((uint)(3)), ((uint)(1)), false);
		this.table9.Name = "table9";
		this.table9.RowSpacing = ((uint)(6));
		this.table9.ColumnSpacing = ((uint)(6));
		// Container child table9.Gtk.Table+TableChild
		this.labelDebtTitle = new global::Gtk.Label();
		this.labelDebtTitle.Name = "labelDebtTitle";
		this.labelDebtTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Debt");
		this.table9.Add(this.labelDebtTitle);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table9[this.labelDebtTitle]));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table9.Gtk.Table+TableChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.nodeviewDebt = new global::Gtk.NodeView();
		this.nodeviewDebt.CanFocus = true;
		this.nodeviewDebt.Name = "nodeviewDebt";
		this.scrolledwindow1.Add(this.nodeviewDebt);
		this.table9.Add(this.scrolledwindow1);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table9[this.scrolledwindow1]));
		w36.TopAttach = ((uint)(1));
		w36.BottomAttach = ((uint)(2));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table9.Gtk.Table+TableChild
		this.table5 = new global::Gtk.Table(((uint)(2)), ((uint)(1)), false);
		this.table5.Name = "table5";
		this.table5.RowSpacing = ((uint)(6));
		this.table5.ColumnSpacing = ((uint)(6));
		// Container child table5.Gtk.Table+TableChild
		this.table10 = new global::Gtk.Table(((uint)(1)), ((uint)(2)), false);
		this.table10.Name = "table10";
		this.table10.RowSpacing = ((uint)(6));
		this.table10.ColumnSpacing = ((uint)(6));
		// Container child table10.Gtk.Table+TableChild
		this.entryInvoiceItemCost = new global::Gtk.Entry();
		this.entryInvoiceItemCost.CanFocus = true;
		this.entryInvoiceItemCost.Name = "entryInvoiceItemCost";
		this.entryInvoiceItemCost.IsEditable = true;
		this.entryInvoiceItemCost.InvisibleChar = '•';
		this.table10.Add(this.entryInvoiceItemCost);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table10[this.entryInvoiceItemCost]));
		w37.LeftAttach = ((uint)(1));
		w37.RightAttach = ((uint)(2));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table10.Gtk.Table+TableChild
		this.label12 = new global::Gtk.Label();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Item cost");
		this.table10.Add(this.label12);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table10[this.label12]));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table5.Add(this.table10);
		global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table5[this.table10]));
		w39.XOptions = ((global::Gtk.AttachOptions)(4));
		w39.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.table7 = new global::Gtk.Table(((uint)(1)), ((uint)(2)), false);
		this.table7.Name = "table7";
		this.table7.RowSpacing = ((uint)(6));
		this.table7.ColumnSpacing = ((uint)(6));
		// Container child table7.Gtk.Table+TableChild
		this.buttonAddInvoiceItem = new global::Gtk.Button();
		this.buttonAddInvoiceItem.CanFocus = true;
		this.buttonAddInvoiceItem.Name = "buttonAddInvoiceItem";
		this.buttonAddInvoiceItem.UseUnderline = true;
		this.buttonAddInvoiceItem.Label = global::Mono.Unix.Catalog.GetString("Add invoice item");
		this.table7.Add(this.buttonAddInvoiceItem);
		global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table7[this.buttonAddInvoiceItem]));
		w40.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table7.Gtk.Table+TableChild
		this.buttonDeleteInvoice = new global::Gtk.Button();
		this.buttonDeleteInvoice.CanFocus = true;
		this.buttonDeleteInvoice.Name = "buttonDeleteInvoice";
		this.buttonDeleteInvoice.UseUnderline = true;
		this.buttonDeleteInvoice.Label = global::Mono.Unix.Catalog.GetString("Delete invoice");
		this.table7.Add(this.buttonDeleteInvoice);
		global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table7[this.buttonDeleteInvoice]));
		w41.LeftAttach = ((uint)(1));
		w41.RightAttach = ((uint)(2));
		w41.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table5.Add(this.table7);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table5[this.table7]));
		w42.TopAttach = ((uint)(1));
		w42.BottomAttach = ((uint)(2));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table9.Add(this.table5);
		global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table9[this.table5]));
		w43.TopAttach = ((uint)(2));
		w43.BottomAttach = ((uint)(3));
		w43.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table8.Add(this.table9);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table8[this.table9]));
		w44.LeftAttach = ((uint)(1));
		w44.RightAttach = ((uint)(2));
		w44.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add(this.table8);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1510;
		this.DefaultHeight = 723;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.SetFocus += new global::Gtk.SetFocusHandler(this.OnSetFocus);
		this.buttonDeleteInvoice.Clicked += new global::System.EventHandler(this.OnButtonDeleteInvoiceClicked);
		this.buttonAddInvoiceItem.Clicked += new global::System.EventHandler(this.OnButtonAddInvoiceItemClicked);
		this.entryInvoiceItemCost.Changed += new global::System.EventHandler(this.OnEntryInvoiceItemCostChanged);
		this.buttonAddInvoice.Clicked += new global::System.EventHandler(this.OnButtonAddInvoiceClicked);
		this.buttonShowInvoiceDetail.Clicked += new global::System.EventHandler(this.OnButtonShowInvoiceDetailClicked);
	}
}
